"""add employees table

Revision ID: 35b10f0db5dc
Revises: 736a9e1f335b
Create Date: 2026-09-03 15:44:13.823135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b10f0db5dc'
down_revision: Union[str, None] = '736a9e1f335b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('job_offer_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Resigned', 'Terminated', name='employee_status'), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_office'), 'employees', ['office'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_office'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
