"""add pending invites table

Revision ID: c0ac16e500b6
Revises: f886b4feccc7
Create Date: 2026-09-08 18:32:35.165200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c0ac16e500b6"
down_revision: Union[str, None] = "f886b4feccc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edited: the autogenerated `sa.Enum(..., name='account_role')` tries
    # to CREATE TYPE account_role again, which already exists (created by
    # 736a9e1f335b for accounts.role) — that fails with DuplicateObjectError.
    # postgresql.ENUM(..., create_type=False) reuses the existing type
    # instead of trying to recreate it.
    account_role = postgresql.ENUM(
        "admin", "people_ops", "hub_lead", "viewer", name="account_role", create_type=False
    )
    op.create_table(
        "pending_invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", account_role, nullable=False),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("invited_by_label", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invited_by_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pending_invites_email"), "pending_invites", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_invites_email"), table_name="pending_invites")
    op.drop_table("pending_invites")
    # ### end Alembic commands ###
