"""add account personalization preferences

Revision ID: f886b4feccc7
Revises: 35b10f0db5dc
Create Date: 2026-09-03 18:04:59.901169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f886b4feccc7'
down_revision: Union[str, None] = '35b10f0db5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))
    op.add_column('accounts', sa.Column('default_office', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('notify_anniversaries', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('accounts', sa.Column('notify_birthdays', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('accounts', sa.Column('notify_new_hires', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'notify_new_hires')
    op.drop_column('accounts', 'notify_birthdays')
    op.drop_column('accounts', 'notify_anniversaries')
    op.drop_column('accounts', 'default_office')
    op.drop_column('accounts', 'theme')
    # ### end Alembic commands ###
