/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnniversariesRouteImport } from './routes/anniversaries'
import { Route as AttendanceReportsRouteImport } from './routes/attendance-reports'
import { Route as AttendanceViolationsRouteImport } from './routes/attendance-violations'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewHiresRouteImport } from './routes/new-hires'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UserManagementRouteImport } from './routes/user-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnniversariesRoute = AnniversariesRouteImport.update({
  id: '/anniversaries',
  path: '/anniversaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceReportsRoute = AttendanceReportsRouteImport.update({
  id: '/attendance-reports',
  path: '/attendance-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceViolationsRoute = AttendanceViolationsRouteImport.update({
  id: '/attendance-violations',
  path: '/attendance-violations',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewHiresRoute = NewHiresRouteImport.update({
  id: '/new-hires',
  path: '/new-hires',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/attendance-reports': typeof AttendanceReportsRoute
  '/attendance-violations': typeof AttendanceViolationsRoute
  '/awards': typeof AwardsRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/attendance-reports': typeof AttendanceReportsRoute
  '/attendance-violations': typeof AttendanceViolationsRoute
  '/awards': typeof AwardsRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/attendance-reports': typeof AttendanceReportsRoute
  '/attendance-violations': typeof AttendanceViolationsRoute
  '/awards': typeof AwardsRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/attendance-reports'
    | '/attendance-violations'
    | '/awards'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/attendance-reports'
    | '/attendance-violations'
    | '/awards'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/attendance-reports'
    | '/attendance-violations'
    | '/awards'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/user-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnniversariesRoute: typeof AnniversariesRoute
  AttendanceReportsRoute: typeof AttendanceReportsRoute
  AttendanceViolationsRoute: typeof AttendanceViolationsRoute
  AwardsRoute: typeof AwardsRoute
  BirthdaysRoute: typeof BirthdaysRoute
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  NewHiresRoute: typeof NewHiresRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  UserManagementRoute: typeof UserManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anniversaries': {
      id: '/anniversaries'
      path: '/anniversaries'
      fullPath: '/anniversaries'
      preLoaderRoute: typeof AnniversariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-reports': {
      id: '/attendance-reports'
      path: '/attendance-reports'
      fullPath: '/attendance-reports'
      preLoaderRoute: typeof AttendanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-violations': {
      id: '/attendance-violations'
      path: '/attendance-violations'
      fullPath: '/attendance-violations'
      preLoaderRoute: typeof AttendanceViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-hires': {
      id: '/new-hires'
      path: '/new-hires'
      fullPath: '/new-hires'
      preLoaderRoute: typeof NewHiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnniversariesRoute: AnniversariesRoute,
  AttendanceReportsRoute: AttendanceReportsRoute,
  AttendanceViolationsRoute: AttendanceViolationsRoute,
  AwardsRoute: AwardsRoute,
  BirthdaysRoute: BirthdaysRoute,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  NewHiresRoute: NewHiresRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  UserManagementRoute: UserManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
