/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnniversariesRouteImport } from './routes/anniversaries'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewHiresRouteImport } from './routes/new-hires'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnniversariesRoute = AnniversariesRouteImport.update({
  id: '/anniversaries',
  path: '/anniversaries',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewHiresRoute = NewHiresRouteImport.update({
  id: '/new-hires',
  path: '/new-hires',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/anniversaries': typeof AnniversariesRoute
  '/birthdays': typeof BirthdaysRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/new-hires': typeof NewHiresRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/settings'
    | '/user-management'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/settings'
    | '/user-management'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/anniversaries'
    | '/birthdays'
    | '/directory'
    | '/login'
    | '/new-hires'
    | '/settings'
    | '/user-management'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnniversariesRoute: typeof AnniversariesRoute
  BirthdaysRoute: typeof BirthdaysRoute
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  NewHiresRoute: typeof NewHiresRoute
  SettingsRoute: typeof SettingsRoute
  UserManagementRoute: typeof UserManagementRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anniversaries': {
      id: '/anniversaries'
      path: '/anniversaries'
      fullPath: '/anniversaries'
      preLoaderRoute: typeof AnniversariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-hires': {
      id: '/new-hires'
      path: '/new-hires'
      fullPath: '/new-hires'
      preLoaderRoute: typeof NewHiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnniversariesRoute: AnniversariesRoute,
  BirthdaysRoute: BirthdaysRoute,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  NewHiresRoute: NewHiresRoute,
  SettingsRoute: SettingsRoute,
  UserManagementRoute: UserManagementRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
